import type { Place } from '@t/place';

export const MOCK_PLACES: Place[] = [
  {
    id: 'mock-hospital-1',
    name: '명지성모병원',
    category: 'hospital',
    vicinity: '서울 영등포구',
    latitude: 37.4939,
    longitude: 126.9037,
  },
  {
    id: 'mock-hospital-2',
    name: '성애병원',
    category: 'hospital',
    vicinity: '서울 영등포구',
    latitude: 37.5108,
    longitude: 126.9142,
  },
  {
    id: 'mock-hospital-3',
    name: '신풍내과의원',
    category: 'hospital',
    vicinity: '서울 영등포구 신풍역 1번 출구 인근',
    latitude: 37.5002,
    longitude: 126.9095,
  },
  {
    id: 'mock-hospital-4',
    name: '영등포병원',
    category: 'hospital',
    vicinity: '서울 영등포구 당산동',
    latitude: 37.5175,
    longitude: 126.9112,
  },
  {
    id: 'mock-hospital-5',
    name: '고려대학교 구로병원',
    category: 'hospital',
    vicinity: '서울 구로구',
    latitude: 37.4925,
    longitude: 126.8851,
  },
  {
    id: 'mock-hospital-6',
    name: '서울가정의학과의원',
    category: 'hospital',
    vicinity: '서울 영등포구 신풍역 교차로 인근',
    latitude: 37.4995,
    longitude: 126.9102,
  },
  {
    id: 'mock-hospital-7',
    name: '연세조은피부과',
    category: 'hospital',
    vicinity: '서울 영등포구 역세권 메디컬 빌딩',
    latitude: 37.5008,
    longitude: 126.9088,
  },
  {
    id: 'mock-hospital-8',
    name: '삼성키즈소아청소년과',
    category: 'hospital',
    vicinity: '서울 영등포구',
    latitude: 37.5015,
    longitude: 126.9091,
  },
  {
    id: 'mock-hospital-9',
    name: '성모안과',
    category: 'hospital',
    vicinity: '서울 영등포구 대림동',
    latitude: 37.4988,
    longitude: 126.9110,
  },
  {
    id: 'mock-hospital-10',
    name: '보라매병원',
    category: 'hospital',
    vicinity: '서울 동작구',
    latitude: 37.4929,
    longitude: 126.9238,
  },
];
